spring.application.name=backend

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/lifeblog}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:Willy123}

server.port=${PORT:8081}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
